"use client"
import styled from 'styled-components'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { TranslationProvider } from '@/utils/context/Translation.context'
import NavBar from '@/components/NavBar'

export const metadata: Metadata = {
  title: 'Dawka Protfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className='w-full min-h-screen flex justify-center items-start bg-dark p-5 text-gray-100 scroll-smooth'>
        <TranslationProvider>
          <PageStyle className='childrenCntr flex justify-center items-center box-border w-5/6 h-[100vh] rounded-2xl'>
            <div className="blackBox bg-primaryDark rounded-2xl absolute z-10 p-5" >
              <NavBar />
              {children}
            </div>
          </PageStyle>
        </TranslationProvider>
      </body>
    </html>
  )
}

const PageStyle = styled.div`
        max-width: min(100%, 1400px);
        position: relative;
        background-color: ${p => p.theme.mainColorDarker};
        overflow: hidden;
        &::before{
            content: "";
            width:100%;
            min-height: 100%;
            position: absolute;
            background: linear-gradient(0deg, transparent, rgb(15, 156, 161)); 
            top: -50%;
            left: -50%;
            transform-origin: bottom right;
            animation: animate 6s linear infinite;
        }
        &::after{
            content: "";
            width: 100%;
            position: absolute;
            background: linear-gradient(0deg, transparent, rgb(15, 156, 161)); 
            top: -50%;
            left: -50%;
            transform-origin: bottom left;
            animation: animate 6s linear infinite;
            animation-delay: -1s;
        }
        .blackBox{
          inset: 2px;
        }
  
    @keyframes animate {
        0%{
            transform: rotate(0deg);
        }
        100%{
            transform: rotate(360deg);
        }
    }
    .main{
      width: 170px;
      height: 170px;
      .navigation{
        width: 40px;
        height: 40px;
        transition: 0.5s;
        span{
          --i: '0';
          --x: '-1';
          --y: '0';
          height: 7px;
          width: 7px;
        }
      }
    }
`
